# Generated by Django 4.0.2 on 2022-02-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='information',
            field=models.TextField(default='', max_length=600),
        ),
    ]
