# Generated by Django 4.0.2 on 2022-02-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_legalservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalservices',
            name='information',
            field=models.TextField(default=''),
        ),
    ]
