# Generated by Django 4.0.2 on 2022-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_legalservices_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalservices',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
