# Generated by Django 4.0.2 on 2022-02-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_legalservices_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
