# Generated by Django 4.0.2 on 2022-02-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_employees_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='information',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='legalservices',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
