# Generated by Django 4.0.2 on 2022-02-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalservices',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
