# Generated by Django 4.0.2 on 2022-02-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_clients_lawyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='email_client',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
