# Generated by Django 4.0.2 on 2022-02-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_clients_email_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clients',
            name='text',
            field=models.TextField(default='spassss', max_length=600),
            preserve_default=False,
        ),
    ]
