# Generated by Django 4.0.2 on 2022-02-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_clients_image_clients_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='email_client',
        ),
    ]
