# Generated by Django 4.0.2 on 2022-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_clients_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
