# Generated by Django 4.0.2 on 2022-02-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_clients_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
